from pathlib import Path

STANDARDIZED_WIDTH = 720
STANDARDIZED_HEIGHT = 1280

RELEASE_MODEL_PATH = Path(__file__).parent / "weights" / "releaseClassifier.onnx"
POSENET_MODEL_PATH = Path(__file__).parent / "weights" / "posenet.tflite"
BALL_DETECTION_MODEL_PATH = Path(__file__).parent / "weights" / "ballDetection.onnx"

RELEASE_CONFIDENCE_THRESHOLD = 0.60

BALL_CONF_RAW_THRESHOLD = 0.30
MAX_BALL_TRACK_FRAMES = 80
BALL_EARLY_STOP_CONF = 0.20
BALL_EARLY_STOP_Y = 200
BALL_EARLY_STOP_MIN_FRAME = 10
BALL_MAX_CANDIDATES_PER_FRAME = 5
BALL_PEAK_NMS_RADIUS = 28

BAT_CONTACT_AUDIO_WINDOW_FRAMES = 5
AUDIO_TARGET_SR = 22050
AUDIO_HIGHPASS_CUTOFF_HZ = 1000.0
AUDIO_SMOOTHING_WINDOW = 512
AUDIO_MIN_PROMINENCE = 0.20
AUDIO_MIN_PEAK_DISTANCE_S = 0.1
