from pathlib import Path

STANDARDIZED_WIDTH = 720
STANDARDIZED_HEIGHT = 1280

RELEASE_MODEL_PATH = Path(__file__).parent / "weights" / "releaseClassifier.onnx"
POSENET_MODEL_PATH = Path(__file__).parent / "weights" / "posenet.tflite"
BALL_DETECTION_MODEL_PATH = Path(__file__).parent / "weights" / "ballDetection.onnx"

RELEASE_CONFIDENCE_THRESHOLD = 0.60

BALL_CONF_RAW_THRESHOLD = 0.30
MAX_BALL_TRACK_FRAMES = 80
BALL_EARLY_STOP_CONF = 0.20
BALL_EARLY_STOP_Y = 200
BALL_EARLY_STOP_MIN_FRAME = 10
BALL_MAX_CANDIDATES_PER_FRAME = 5
BALL_PEAK_NMS_RADIUS = 28
BALL_DYNAMIC_SEARCH_MIN_HISTORY = 3
BALL_DYNAMIC_SEARCH_BASE_RADIUS_PX = 140.0
BALL_DYNAMIC_SEARCH_RADIUS_SCALE = 1.5
BALL_DYNAMIC_SEARCH_MAX_RADIUS_PX = 260.0
BALL_DYNAMIC_SEARCH_MAX_RECOVERY_RADIUS_PX = 340.0
TRACK_REBUILDER_RANSAC_ITERS = 1200
TRACK_REBUILDER_INLIER_THRESH = 14.0
TRACK_REBUILDER_SUPPORT_THRESH = 18.0
TRACK_REBUILDER_MIN_INLIERS = 5
TRACK_REBUILDER_MIN_SEGMENT_INLIERS = 3
TRACK_REBUILDER_MIN_PRE_BOUNCE_DETS = 3
TRACK_REBUILDER_MIN_POST_BOUNCE_DETS = 2
TRACK_REBUILDER_MAX_FRAME_GAP = 6
TRACK_REBUILDER_TRACK_BEAM_WIDTH = 12
TRACK_REBUILDER_START_WINDOW = 12
TRACK_REBUILDER_START_CONF_WEIGHT = 8.0
TRACK_REBUILDER_CONTINUITY_CONF_WEIGHT = 10.0
TRACK_REBUILDER_DISTANCE_WEIGHT = 0.03
TRACK_REBUILDER_PREDICTION_WEIGHT = 0.12
TRACK_REBUILDER_ACCELERATION_WEIGHT = 0.08
TRACK_REBUILDER_MAX_STEP_PIXELS = 180.0
TRACK_REBUILDER_MAX_PREDICTION_ERROR = 140.0
TRACK_REBUILDER_MIN_STABLE_SUPPORT = 6
TRACK_REBUILDER_MAX_UNSUPPORTED_RUN = 3
TRACK_REBUILDER_MIN_TAIL_START_FRAMES = 8

BAT_CONTACT_AUDIO_WINDOW_FRAMES = 5
AUDIO_TARGET_SR = 22050
AUDIO_HIGHPASS_CUTOFF_HZ = 1000.0
AUDIO_SMOOTHING_WINDOW = 512
AUDIO_MIN_PROMINENCE = 0.20
AUDIO_MIN_PEAK_DISTANCE_S = 0.1

